apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quack-stack-db
  template:
    metadata:
      labels:
        app: quack-stack-db
    spec:
      containers:
        - name: quack-stack-db-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: quack-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: quack-config
                  key: DB_PASS
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: quack-config
                  key: DB_NAME
