apiVersion: batch/v1
kind: Job
metadata:
  name: init-duck-table-job
spec:
  template:
    spec:
      containers:
        - name: init-duck-table
          image: postgres:14-alpine
          command: ["sh", "-c"]
          args:
            - |
              echo "
              CREATE TABLE IF NOT EXISTS \"Duck\" (
                \"Id\" SERIAL PRIMARY KEY,
                \"Name\" VARCHAR,
                \"Species\" VARCHAR,
                \"Age\" REAL,
                \"Weight\" REAL,
                \"Color\" VARCHAR,
                \"IsMigratory\" BOOLEAN,
                \"CanFly\" BOOLEAN,
                \"QuackVolume\" INT,
                \"Mood\" VARCHAR,
                \"FavoriteFood\" VARCHAR,
                \"IsLeader\" VARCHAR,
                \"CreatedAt\" TIMESTAMP DEFAULT NOW()
              );

              INSERT INTO \"Duck\" (
                \"Name\", \"Species\", \"Age\", \"Weight\", \"Color\", \"IsMigratory\", \"CanFly\",
                \"QuackVolume\", \"Mood\", \"FavoriteFood\", \"IsLeader\"
              )
              VALUES
                ('Daffy', 'Mallard', 4.5, 1.2, 'black', true, true, 8, 'angry', 'corn', 'false'),
                ('Donald', 'Pekin', 3.2, 1.5, 'white', false, false, 5, 'grumpy', 'bread', 'true'),
                ('Daisy', 'Pekin', 2.8, 1.3, 'white', true, true, 6, 'happy', 'peas', 'false'),
                ('Howard', 'Muscovy', 5.0, 2.0, 'green', false, true, 7, 'confused', 'bugs', 'true'),
                ('Quackers', 'Call', 1.5, 0.9, 'yellow', true, true, 9, 'excited', 'lettuce', 'false');
              " | psql -h database -U admin -d ducks
          env:
            - name: PGPASSWORD
              value: admin
      restartPolicy: OnFailure
